
(function(){
const C = window.JSLCOIN_CONFIG;
const $ = (id)=>document.getElementById(id);
const fmt = (n)=>Number(n||0).toLocaleString('en-US') + ' ' + C.symbol;
const now = ()=>new Date().toISOString();
const short = (s)=> s ? (s.length>18 ? s.slice(0,10)+'…'+s.slice(-6) : s) : '—';
function wallet(seed){ let h=2166136261; for(let i=0;i<seed.length;i++){ h^=seed.charCodeAt(i); h=Math.imul(h,16777619);} return 'JSLΩ-'+Math.abs(h).toString(16).toUpperCase().padStart(8,'0')+'-'+Date.now().toString(36).toUpperCase().slice(-5); }
function defaultState(){
  const ow = wallet(C.ownerEmail+'genesis');
  return {version:C.version, createdAt:now(), currentUser:null, users:[{email:C.ownerEmail, phone:'', name:'Genesis Owner', password:'', role:'owner', wallet:ow, balance:C.initialSupply, createdAt:now()}], transactions:[{id:'GENESIS-OMEGA-5-0', time:now(), type:'GENESIS', from:'Ω', to:ow, amount:C.initialSupply, status:'confirmed', note:'Initial supply issued to Genesis Owner'}]};
}
function load(){let s=null; try{s=JSON.parse(localStorage.getItem(C.storageKey)||'null')}catch(e){} if(!s||!s.users||!s.transactions){s=defaultState(); save(s)} return s;}
function save(s){localStorage.setItem(C.storageKey, JSON.stringify(s));}
function findUser(s, key){key=(key||'').trim().toLowerCase(); return s.users.find(u=>(u.email||'').toLowerCase()===key || (u.phone||'')===key || (u.wallet||'').toLowerCase()===key);}
function current(s){return s.users.find(u=>u.wallet===s.currentUser)||null;}
function requireLogin(){const s=load(); if(!current(s)){ location.href='index.html'; return null;} return s;}
function header(active){
 const s=load(), u=current(s);
 const nav=[['dashboard.html','Dashboard'],['wallet.html','Wallet'],['transactions.html','Transactions'],['ownerpage.html','Owner']].map(([href,label])=>`<a class="${active===label?'active':''}" href="${href}">${label}</a>`).join('');
 const el=$('siteHeader'); if(el) el.innerHTML=`<div class="topbar"><div class="navwrap"><a class="brand" href="index.html"><span class="mark"></span><span><h1>JSLCoin Omega</h1><p>5.0 Commercial Release</p></span></a><nav class="nav">${nav}${u?'<button id="logoutBtn">Logout</button>':''}</nav></div></div>`;
 const out=$('logoutBtn'); if(out) out.onclick=()=>{const s=load(); s.currentUser=null; save(s); location.href='index.html'};
}
function footer(){const el=$('siteFooter'); if(el) el.innerHTML=`<div class="footer">© 2026 JSL-ian Technologies. All rights reserved.<br>JSL-ian™ and JSLCoin™ are trademarks of JSL-ian Technologies.</div>`;}
function stats(){const s=load(); return {users:s.users.length, wallets:s.users.length, total:s.users.reduce((a,u)=>a+Number(u.balance||0),0), tx:s.transactions.length};}
window.JSLOmega={load,save,findUser,current,requireLogin,fmt,short,stats,header,footer,now,wallet,C,
 initIndex(){header('Home'); footer(); const s=load(); const u=current(s); const st=stats(); ['ownerEmail','supply','userCount','txCount'].forEach(id=>$(id)&&($(id).textContent={ownerEmail:C.ownerEmail,supply:fmt(C.initialSupply),userCount:st.users,txCount:st.tx}[id]));
  if($('loginForm')) $('loginForm').onsubmit=(e)=>{e.preventDefault(); let key=$('loginKey').value, pass=$('password').value, name=$('name').value, phone=$('phone').value; let u=findUser(s,key); if(!u){ if(!key){alert('Email or phone required');return} u={email:key.includes('@')?key:'', phone:key.includes('@')?phone:key, name:name||key, password:pass||'', role:(key.toLowerCase()===C.ownerEmail?'owner':'user'), wallet:wallet(key+phone+name), balance:0, createdAt:now()}; s.users.push(u); s.transactions.push({id:'USER-'+Date.now(),time:now(),type:'REGISTER',from:'Ω',to:u.wallet,amount:0,status:'confirmed',note:'User registered and wallet auto-created'}); } else if(u.password && u.password!==pass){alert('Password incorrect');return} s.currentUser=u.wallet; save(s); location.href='dashboard.html'; };
  if(u && $('enterBtn')) $('enterBtn').textContent='Enter Dashboard'; },
 initDashboard(){const s=requireLogin(); if(!s)return; header('Dashboard'); footer(); const u=current(s), st=stats(); $('account').textContent=u.email||u.phone||u.name; $('balance').textContent=fmt(u.balance); $('wallet').textContent=u.wallet; $('owner').textContent=C.ownerEmail; $('total').textContent=fmt(st.total); $('omegaEndpoint').textContent=C.omegaEndpoint; this.renderRecent(s.transactions.slice(-6).reverse()); },
 renderRecent(list){const tbody=$('recentBody'); if(!tbody)return; tbody.innerHTML=list.map(t=>`<tr><td>${new Date(t.time).toLocaleString()}</td><td>${t.type}</td><td>${fmt(t.amount)}</td><td class="mono">${short(t.from)}</td><td class="mono">${short(t.to)}</td><td>${t.status}</td></tr>`).join('')||'<tr><td colspan="6">No transactions yet.</td></tr>';},
 initWallet(){const s=requireLogin(); if(!s)return; header('Wallet'); footer(); const u=current(s); $('walletAddress').textContent=u.wallet; $('walletBalance').textContent=fmt(u.balance); $('identity').textContent=[u.email,u.phone].filter(Boolean).join(' / ')||u.name; $('sendForm').onsubmit=(e)=>{e.preventDefault(); let toKey=$('to').value.trim(), amount=Number($('amount').value); let to=findUser(s,toKey); if(!to){alert('Receiver not found');return} if(amount<=0||u.balance<amount){alert('Invalid amount or insufficient balance');return} u.balance-=amount; to.balance+=amount; s.transactions.push({id:'TX-'+Date.now(),time:now(),type:'SEND',from:u.wallet,to:to.wallet,amount,status:'confirmed',note:'Wallet transfer'}); save(s); location.href='transactions.html';};},
 initTransactions(){const s=requireLogin(); if(!s)return; header('Transactions'); footer(); const u=current(s); const list=s.transactions.filter(t=>t.from===u.wallet||t.to===u.wallet||u.role==='owner').slice().reverse(); const body=$('txBody'); body.innerHTML=list.map(t=>`<tr><td>${new Date(t.time).toLocaleString()}</td><td>${t.id}</td><td>${t.type}</td><td>${fmt(t.amount)}</td><td class="mono">${short(t.from)}</td><td class="mono">${short(t.to)}</td><td><span class="pill">${t.status}</span></td><td>${t.note||''}</td></tr>`).join('')||'<tr><td colspan="8">No transactions yet.</td></tr>';},
 initOwner(){const s=requireLogin(); if(!s)return; header('Owner'); footer(); const u=current(s); if(u.role!=='owner'){ $('ownerOnly').innerHTML='<div class="notice bad">Owner access only.</div>'; return;} const st=stats(); $('ownerEmail').textContent=C.ownerEmail; $('supply').textContent=fmt(st.total); $('users').textContent=st.users; $('wallets').textContent=st.wallets; $('omegaEndpoint').textContent=C.omegaEndpoint; $('mintForm').onsubmit=(e)=>{e.preventDefault(); let to=findUser(s,$('mintTo').value), amount=Number($('mintAmount').value); if(!to||amount<=0){alert('Invalid receiver or amount');return} to.balance+=amount; s.transactions.push({id:'MINT-'+Date.now(),time:now(),type:'MINT',from:'OWNER',to:to.wallet,amount,status:'confirmed',note:'Owner mint'}); save(s); location.reload();}; $('burnForm').onsubmit=(e)=>{e.preventDefault(); let amount=Number($('burnAmount').value); if(amount<=0||u.balance<amount){alert('Invalid burn amount');return} u.balance-=amount; s.transactions.push({id:'BURN-'+Date.now(),time:now(),type:'BURN',from:u.wallet,to:'Ω',amount,status:'confirmed',note:'Owner burn'}); save(s); location.reload();}; const ub=$('userBody'); ub.innerHTML=s.users.map(x=>`<tr><td>${x.email||'—'}</td><td>${x.phone||'—'}</td><td>${x.name||'—'}</td><td>${x.role}</td><td>${fmt(x.balance)}</td><td class="mono">${short(x.wallet)}</td></tr>`).join('');}
};
})();
