(function(){
'use strict';
const KEY='JSLCoinOmega50StableUpgrade';
const OWNER='jingxingwei@hotmail.com';
const SUPPLY=1000000000;
const OMEGA='https://omega.jsl-ian.com';
function $(id){return document.getElementById(id)}
function now(){return new Date().toLocaleString()}
function walletSeed(id){let s=0;id=String(id||'');for(let i=0;i<id.length;i++)s=(s*31+id.charCodeAt(i))>>>0;return 'JSLΩ-'+s.toString(16).toUpperCase().padStart(8,'0')}
function initState(){const ownerWallet=walletSeed(OWNER);return {current:null,supply:SUPPLY,omega:OMEGA,users:{[OWNER]:{email:OWNER,phone:'',name:'Genesis Owner',role:'owner',wallet:ownerWallet,balance:SUPPLY}},ledger:[{id:'GENESIS-OMEGA-5-0',time:now(),type:'GENESIS',from:'Ω',to:OWNER,amount:SUPPLY,status:'confirmed',note:'Initial supply issued to Genesis Owner',closure:'L^n=-1'}]}}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(!s.users||!s.users[OWNER])throw new Error('bad state');return s}}catch(e){}const s=initState();save(s);return s}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function idFromInputs(){const email=($('email')?.value||'').trim().toLowerCase();const phone=($('phone')?.value||'').trim();return email||phone}
function safeNum(n){n=Number(n);return Number.isFinite(n)?n:0}
function fmt(n){return safeNum(n).toLocaleString()+' JSL'}
function msg(text,type='ok'){const el=$('msg')||$('status');if(el)el.innerHTML='<div class="notice '+type+'">'+text+'</div>'}
function getUserByIdentity(s,id){id=(id||'').trim().toLowerCase();if(!id)return null;if(s.users[id])return s.users[id];return Object.values(s.users).find(u=>u.email===id||u.phone===id||u.wallet===id)||null}
function ensureUser(id,extra={}){let s=load();id=(id||'').trim().toLowerCase();if(!id)return null;let key=id;let existing=getUserByIdentity(s,id);if(existing)return existing;const isEmail=id.includes('@');s.users[key]={email:isEmail?id:'',phone:isEmail?'':id,name:extra.name||'',role:'user',wallet:walletSeed(id),balance:0};s.ledger.push({id:'USER-'+Date.now(),time:now(),type:'REGISTER',from:'Ω',to:key,amount:0,status:'confirmed',note:'User registered and wallet auto-created',closure:'L^n=-1'});save(s);return s.users[key]}
function current(){const s=load();return s.current?getUserByIdentity(s,s.current):null}
function requireLogin(){if(!current()){location.href='wallet-login.html';return false}return true}
function linkActive(){const p=(location.pathname.split('/').pop()||'index.html');document.querySelectorAll('.nav a').forEach(a=>{const href=a.getAttribute('href')||'';if(href===p)a.classList.add('active')})}
function renderIndex(){if(!$('homeOwner'))return;const s=load();$('homeOwner').textContent=OWNER;$('homeSupply').textContent=fmt(s.supply);$('homeOmega').innerHTML='<a class="pill" href="'+OMEGA+'">omega.jsl-ian.com</a>';$('runtimeStatus').innerHTML='<div class="notice ok">omega5.jsl active. JSL closure: L^n=-1. Balance engine ready.</div>'}
function renderDashboard(){if(!$('currentUser'))return;if(!requireLogin())return;const s=load(),u=current();$('currentUser').textContent=u.email||u.phone||u.wallet;$('role').textContent=u.role;$('balance').textContent=fmt(u.balance);$('walletAddress').textContent=u.wallet;$('dashOwner').textContent=OWNER;$('dashSupply').textContent=fmt(s.supply);$('dashOmega').textContent=OMEGA;const rows=s.ledger.slice(-8).reverse().map(txRow).join('');$('ledgerRows').innerHTML=rows||'<tr><td colspan="6">No transactions yet.</td></tr>'}
function renderWallet(){if(!$('walletAddress'))return;if(!requireLogin())return;const u=current();$('walletAddress').textContent=u.wallet;$('walletBalance').textContent=fmt(u.balance);$('walletRole').textContent=u.role}
function txRow(x){return '<tr><td>'+(x.time||'')+'</td><td>'+(x.type||'')+'</td><td>'+(x.from||'')+'</td><td>'+(x.to||'')+'</td><td>'+fmt(x.amount)+'</td><td><span class="pill">'+(x.status||'confirmed')+'</span></td></tr>'}
function ledgerRow(x,i){return '<tr><td>'+i+'</td><td>'+(x.id||'')+'</td><td>'+(x.type||'')+'</td><td>'+(x.from||'')+'</td><td>'+(x.to||'')+'</td><td>'+fmt(x.amount)+'</td><td>'+(x.closure||'L^n=-1')+'</td></tr>'}
function renderTransactions(){if(!$('txRows'))return;const s=load();$('txRows').innerHTML=s.ledger.slice().reverse().map(txRow).join('')}
function renderLedger(){if(!$('fullLedgerRows'))return;const s=load();$('fullLedgerRows').innerHTML=s.ledger.map(ledgerRow).join('')}
function renderOwner(){if(!$('ownerArea'))return;const s=load(),u=current();if(!u||u.role!=='owner'){$('guard').innerHTML='<div class="notice err">Owner only. Login as Genesis Owner to use Owner Console.</div><p><button class="btn good" onclick="JSLApp.ownerLogin()">Owner Login</button> <a class="btn" href="wallet-login.html">Wallet Login</a></p>';return}$('guard').innerHTML='<div class="notice ok">Owner verified: '+OWNER+'</div>';$('ownerArea').classList.remove('hide');$('ownerEmail').textContent=OWNER;$('ownerSupply').textContent=fmt(s.supply);$('ownerUsers').textContent=Object.keys(s.users).length;$('ownerWallet').textContent=s.users[OWNER].wallet;$('userRows').innerHTML=Object.values(s.users).map(u=>'<tr><td>'+u.email+'</td><td>'+u.phone+'</td><td>'+u.name+'</td><td>'+u.role+'</td><td>'+u.wallet+'</td><td>'+fmt(u.balance)+'</td></tr>').join('')}
function send(){if(!requireLogin())return;let s=load();const senderKey=s.current;const sender=getUserByIdentity(s,senderKey);const toRaw=($('to')?.value||'').trim().toLowerCase();const amount=safeNum($('amount')?.value);if(!toRaw||amount<=0){msg('Enter receiver and valid amount.','err');return}if(sender.balance<amount){msg('Insufficient balance.','err');return}ensureUser(toRaw);s=load();const receiver=getUserByIdentity(s,toRaw);const receiverKey=Object.keys(s.users).find(k=>s.users[k]===receiver) || toRaw;s.users[senderKey].balance-=amount;s.users[receiverKey].balance+=amount;s.ledger.push({id:'TX-'+Date.now(),time:now(),type:'SEND',from:senderKey,to:receiverKey,amount,status:'confirmed',note:'Wallet transfer',closure:'L^n=-1'});save(s);msg('Transfer complete. Balance recalculated.','ok');setTimeout(()=>location.href='dashboard.html',500)}
window.JSLApp={register:function(){const id=idFromInputs();if(!id){msg('Enter email or phone.','err');return}const name=($('name')?.value||'').trim();ensureUser(id,{name});const s=load();s.current=id;save(s);msg('Wallet created.','ok');setTimeout(()=>location.href='dashboard.html',500)},login:function(){const id=idFromInputs();if(!id){msg('Enter email or phone.','err');return}ensureUser(id);const s=load();s.current=id;save(s);msg('Login success.','ok');setTimeout(()=>location.href='dashboard.html',500)},ownerLogin:function(){const s=load();s.current=OWNER;save(s);location.href='ownerpage.html'},logout:function(){const s=load();s.current=null;save(s);location.href='wallet-login.html'},send,mint:function(){let s=load(),u=current();if(!u||u.role!=='owner')return;const to=($('mintTo')?.value||'').trim().toLowerCase();const amount=safeNum($('mintAmount')?.value);if(!to||amount<=0)return msg('Enter target and amount.','err');ensureUser(to);s=load();const receiver=getUserByIdentity(s,to);const rkey=Object.keys(s.users).find(k=>s.users[k]===receiver)||to;s.users[rkey].balance+=amount;s.supply+=amount;s.ledger.push({id:'MINT-'+Date.now(),time:now(),type:'MINT',from:OWNER,to:rkey,amount,status:'confirmed',note:'Owner mint',closure:'L^n=-1'});save(s);location.reload()},burn:function(){let s=load(),u=current();const amount=safeNum($('burnAmount')?.value);if(!u||u.role!=='owner')return;if(amount<=0||s.users[OWNER].balance<amount)return msg('Invalid burn amount.','err');s.users[OWNER].balance-=amount;s.supply-=amount;s.ledger.push({id:'BURN-'+Date.now(),time:now(),type:'BURN',from:OWNER,to:'Ω',amount,status:'confirmed',note:'Owner burn',closure:'L^n=-1'});save(s);location.reload()},resetDemo:function(){localStorage.removeItem(KEY);location.reload()}};
document.addEventListener('DOMContentLoaded',function(){linkActive();renderIndex();renderDashboard();renderWallet();renderTransactions();renderLedger();renderOwner()});
})();
