const CORS={"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,authorization"};
const SUPPLY=1000000000,SESSION_TTL=43200,RESET_TTL=900,enc=new TextEncoder();
const clean=v=>String(v??"").trim(),norm=v=>clean(v).toLowerCase(),now=()=>new Date().toISOString(),uid=p=>`${p}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;
const wallet=()=>`JSLΩ-${crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase()}`;
function json(d,s=200){return new Response(JSON.stringify(d,null,2),{status:s,headers:{...CORS,"content-type":"application/json"}})}
async function body(r){try{return await r.json()}catch{return {}}}
async function shaBytes(data){const b=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function hashPassword(password,salt=crypto.randomUUID()){if(clean(password).length<8)throw new Error("Password must be at least 8 characters");const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:enc.encode(salt),iterations:150000},key,256);return {salt,hash:[...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,"0")).join("")}}
async function verify(u,p){const h=await hashPassword(p,u.password_salt);return h.hash===u.password_hash}
async function setting(env,k){return (await env.DB.prepare("SELECT value FROM settings WHERE key=?").bind(k).first())?.value??""}
async function setSetting(env,k,v){await env.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(k,String(v)).run()}
async function findUser(env,q){q=norm(q);if(!q)return null;return env.DB.prepare("SELECT * FROM users WHERE lower(username)=? OR lower(email)=? OR phone=? OR lower(wallet)=? LIMIT 1").bind(q,q,clean(q),q).first()}
async function accountLabel(env,a){if(a==="MINT")return "Ω";if(a==="TREASURY")return "Treasury";if(a.startsWith("USER:")){const u=await env.DB.prepare("SELECT display_name FROM users WHERE id=?").bind(a.slice(5)).first();return u?.display_name||a}return a}
async function balance(env,id){const a=`USER:${id}`;const r=await env.DB.prepare("SELECT COALESCE((SELECT SUM(amount) FROM ledger WHERE to_account=? AND status='confirmed'),0)-COALESCE((SELECT SUM(amount) FROM ledger WHERE from_account=? AND status='confirmed'),0) AS balance").bind(a,a).first();return Number(r?.balance||0)}
async function treasuryBalance(env){const r=await env.DB.prepare("SELECT COALESCE((SELECT SUM(amount) FROM ledger WHERE to_account='TREASURY' AND status='confirmed'),0)-COALESCE((SELECT SUM(amount) FROM ledger WHERE from_account='TREASURY' AND status='confirmed'),0) AS balance").first();return Number(r?.balance||0)}
async function pub(env,u){return {id:u.id,username:u.username,displayName:u.display_name,email:u.email,phone:u.phone,wallet:u.wallet,role:u.role,balance:await balance(env,u.id)}}
async function session(env,u){const t=crypto.randomUUID()+crypto.randomUUID();await env.KV.put(`session:${t}`,JSON.stringify({userId:u.id,role:u.role}),{expirationTtl:SESSION_TTL});return t}
async function auth(req,env,role){const t=clean(req.headers.get("authorization")).replace(/^Bearer\s+/i,"");if(!t)throw new Error("Login required");const s=await env.KV.get(`session:${t}`,"json");if(!s)throw new Error("Login required");const u=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(s.userId).first();if(!u)throw new Error("Account not found");if(role&&u.role!==role)throw new Error("Permission denied");return {u,t}}
function amount(v){const n=Number(v);if(!Number.isSafeInteger(n)||n<=0)throw new Error("Amount must be a positive whole number");return n}
async function addTx(env,type,from,to,n,note=""){await env.DB.prepare("INSERT INTO ledger(id,tx_type,from_account,to_account,amount,note,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(uid("TX"),type,from,to,n,note,"confirmed",now()).run()}
async function txList(env,where="",binds=[]){const rows=(await env.DB.prepare(`SELECT * FROM ledger ${where} ORDER BY created_at DESC LIMIT 500`).bind(...binds).all()).results||[];return Promise.all(rows.map(async t=>({id:t.id,type:t.tx_type,fromLabel:await accountLabel(env,t.from_account),toLabel:await accountLabel(env,t.to_account),amount:t.amount,status:t.status,createdAt:t.created_at,note:t.note})))}
async function sendResetEmail(env,to,code){if(!env.RESEND_API_KEY||!env.RESET_FROM_EMAIL)return false;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:env.RESET_FROM_EMAIL,to:[to],subject:"JSLCoin reset code",html:`<p>Your reset code is <strong>${code}</strong>. It expires in 15 minutes.</p>`})});return r.ok}
async function handle(req,env){
 if(req.method==="OPTIONS")return new Response(null,{headers:CORS});if(!env.DB)throw new Error("D1 binding DB is missing");if(!env.KV)throw new Error("KV binding KV is missing");
 const path=new URL(req.url).pathname.replace(/\/$/,"")||"/";
 if(path==="/"||path==="/status"){const ownerId=await setting(env,"owner_id"),genesis=(await setting(env,"genesis"))==="true",totalSupply=Number(await setting(env,"total_supply")||0),users=(await env.DB.prepare("SELECT COUNT(*) n FROM users").first())?.n||0,ledgerCount=(await env.DB.prepare("SELECT COUNT(*) n FROM ledger").first())?.n||0;return json({ok:true,coin:"JSLCoin",version:"7.1",ownerReady:!!ownerId,genesis,totalSupply,treasury:await treasuryBalance(env),users,ledgerCount,d1:true,kv:true})}
 if(path==="/owner/setup-or-login"){const x=await body(req),identity=clean(x.identity),password=String(x.password||"");let oid=await setting(env,"owner_id"),u=oid?await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(oid).first():null;if(!u){if(!env.OWNER_SETUP_KEY)throw new Error("OWNER_SETUP_KEY secret is missing");if(clean(x.setupKey)!==String(env.OWNER_SETUP_KEY))throw new Error("Invalid setup key");if(!identity)throw new Error("Owner identity required");const hp=await hashPassword(password),id="owner",email=identity.includes("@")?norm(identity):"",wa=identity.includes("@")?wallet():identity;await env.DB.prepare("INSERT INTO users(id,username,display_name,email,phone,wallet,role,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,"owner","JSL-ian Owner",email,"",wa,"owner",hp.hash,hp.salt,now()).run();await setSetting(env,"owner_id",id);u=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(id).first()}else{if(![u.username,u.email,u.wallet].some(v=>norm(v)===norm(identity)))throw new Error("Owner account not found");if(!await verify(u,password))throw new Error("Invalid password")}const t=await session(env,u);return json({ok:true,token:t,user:await pub(env,u)})}
 if(path==="/genesis"){const {u}=await auth(req,env,"owner");if((await setting(env,"genesis"))==="true")return json({ok:true,message:"Genesis already completed"});await env.DB.batch([env.DB.prepare("INSERT INTO ledger(id,tx_type,from_account,to_account,amount,note,status,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(uid("TX"),"GENESIS","MINT",`USER:${u.id}`,SUPPLY,"Initial supply","confirmed",now()),env.DB.prepare("UPDATE settings SET value='true' WHERE key='genesis'"),env.DB.prepare("UPDATE settings SET value=? WHERE key='total_supply'").bind(String(SUPPLY))]);return json({ok:true,message:"Genesis completed"})}
 if(path==="/register"){if((await setting(env,"genesis"))!=="true")throw new Error("Genesis must be completed first");const x=await body(req);for(const q of [x.username,x.email,x.phone])if(clean(q)&&await findUser(env,q))throw new Error("Account already exists");const hp=await hashPassword(String(x.password||"")),id=uid("USER"),u={id,username:norm(x.username)||`user-${Date.now()}`,display_name:clean(x.name)||norm(x.username)||"User",email:norm(x.email),phone:clean(x.phone),wallet:wallet(),role:"user",password_hash:hp.hash,password_salt:hp.salt,created_at:now()};await env.DB.prepare("INSERT INTO users(id,username,display_name,email,phone,wallet,role,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(u.id,u.username,u.display_name,u.email,u.phone,u.wallet,u.role,u.password_hash,u.password_salt,u.created_at).run();const t=await session(env,u);return json({ok:true,token:t,user:await pub(env,u)})}
 if(path==="/login"){const x=await body(req),u=await findUser(env,x.identity);if(!u)throw new Error("Account not found");if(!await verify(u,String(x.password||"")))throw new Error("Invalid password");const t=await session(env,u);return json({ok:true,token:t,user:await pub(env,u)})}
 if(path==="/logout"){const t=clean(req.headers.get("authorization")).replace(/^Bearer\s+/i,"");if(t)await env.KV.delete(`session:${t}`);return json({ok:true})}
 if(path==="/me"){const {u}=await auth(req,env);return json({ok:true,user:await pub(env,u)})}
 if(path==="/send"||path==="/owner/send"){const {u}=await auth(req,env,path==="/owner/send"?"owner":undefined),x=await body(req),to=await findUser(env,x.to),n=amount(x.amount);if(!to)throw new Error("Recipient not found");if(to.id===u.id)throw new Error("Cannot send to yourself");if(await balance(env,u.id)<n)throw new Error("Insufficient balance");await addTx(env,path==="/owner/send"?"OWNER_SEND":"SEND",`USER:${u.id}`,`USER:${to.id}`,n,"Transfer");return json({ok:true,message:"Transfer completed"})}
 if(path==="/owner/treasury"){const {u}=await auth(req,env,"owner"),x=await body(req),n=amount(x.amount);if(await balance(env,u.id)<n)throw new Error("Owner balance insufficient");await addTx(env,"TREASURY_FUND",`USER:${u.id}`,"TREASURY",n,"Treasury funding");return json({ok:true,message:"Treasury funded"})}
 if(path==="/buy"){const {u}=await auth(req,env),x=await body(req),n=amount(x.amount);if(await treasuryBalance(env)<n)throw new Error("Treasury balance insufficient");await addTx(env,"BUY","TREASURY",`USER:${u.id}`,n,"Buy from treasury");return json({ok:true,message:"Buy completed"})}
 if(path==="/sell"){const {u}=await auth(req,env),x=await body(req),n=amount(x.amount);if(await balance(env,u.id)<n)throw new Error("Insufficient balance");await addTx(env,"SELL",`USER:${u.id}`,"TREASURY",n,"Sell to treasury");return json({ok:true,message:"Sell completed"})}
 if(path==="/transactions"){const {u}=await auth(req,env),a=`USER:${u.id}`;return json({ok:true,transactions:u.role==="owner"?await txList(env):await txList(env,"WHERE from_account=? OR to_account=?",[a,a])})}
 if(path==="/ledger"){await auth(req,env,"owner");return json({ok:true,transactions:await txList(env)})}
 if(path==="/users"){await auth(req,env,"owner");const rows=(await env.DB.prepare("SELECT * FROM users ORDER BY created_at").all()).results||[];return json({ok:true,users:await Promise.all(rows.map(u=>pub(env,u)))})}
 if(path==="/forgot-password"){const x=await body(req),u=await findUser(env,x.identity);if(!u)return json({ok:true,message:"If the account exists, a reset code has been sent."});const code=String(Math.floor(100000+Math.random()*900000)),hash=await shaBytes(enc.encode(code));await env.KV.put(`reset:${u.id}`,hash,{expirationTtl:RESET_TTL});const sent=u.email?await sendResetEmail(env,u.email,code):false;if(String(env.RESET_TEST_MODE)==="true")return json({ok:true,message:"Reset code created.",testCode:code});if(!sent)throw new Error("No reset delivery channel configured");return json({ok:true,message:"Reset code sent."})}
 if(path==="/reset-password"){const x=await body(req),u=await findUser(env,x.identity);if(!u)throw new Error("Reset code invalid or expired");const stored=await env.KV.get(`reset:${u.id}`),given=await shaBytes(enc.encode(String(x.code||"")));if(!stored||stored!==given)throw new Error("Reset code invalid or expired");const hp=await hashPassword(String(x.password||""));await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=? WHERE id=?").bind(hp.hash,hp.salt,u.id).run();await env.KV.delete(`reset:${u.id}`);return json({ok:true,message:"Password updated"})}
 if(path==="/audit"){await auth(req,env,"owner");const supply=Number(await setting(env,"total_supply")||0),users=(await env.DB.prepare("SELECT COALESCE(SUM((SELECT COALESCE(SUM(amount),0) FROM ledger l1 WHERE l1.to_account='USER:'||u.id AND l1.status='confirmed')-(SELECT COALESCE(SUM(amount),0) FROM ledger l2 WHERE l2.from_account='USER:'||u.id AND l2.status='confirmed')),0) total FROM users u").first())?.total||0,treasury=await treasuryBalance(env),total=Number(users)+Number(treasury),ok=total===supply;return json({ok,message:ok?"Audit passed: balances equal total supply.":`Audit failed: ${total} != ${supply}`})}
 return json({ok:false,error:"Not found",path},404)
}
export default{async fetch(req,env){try{return await handle(req,env)}catch(e){return json({ok:false,error:e.message||String(e)},400)}}};
